name: apiClient
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  code_builder: ^4.10.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.0
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^3.1.0