name: apiClient
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  code_builder: ^4.10.0
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  devicelocale: ^0.7.0
  dio: ^5.4.0
  equatable: ^2.0.5
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  injector: ^3.0.0
  json_annotation: ^4.8.1
  location: ^5.0.3
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  synchronized: ^3.1.0+1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  lints: ^2.0.1
  very_good_analysis: ^3.1.0