name: storage
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  lints: ^2.0.1
  very_good_analysis: ^3.1.0