name: stadtplan
description: Mobile native version of www.maps.stadt-zuerich.ch
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  code_builder: ^4.10.0
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dart_style: ^2.3.4
  dio: ^5.4.0
  equatable: ^2.0.5
  event_bus: ^2.0.0
  fimber: ^0.7.0
  firebase_core: ^2.25.5
  firebase_performance: ^0.9.3+13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^5.8.0
  flutter_localization: ^0.2.0
  flutter_platform_widgets: ^6.0.2
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.7.0
  google_maps_flutter_platform_interface: ^2.6.0
  http: ^1.2.0
  injector: ^3.0.0
  json_annotation: ^4.8.1
  location: ^5.0.3
  lottie: ^3.1.0
  map_launcher: ^3.2.0
  mocktail: ^1.0.3
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^5.0.1
  permission_handler: ^11.3.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  sprintf: ^7.0.0
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  uuid: ^4.4.0
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2

  apiClient:
    path: packages/api_client

  storage:
    path: packages/storage

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  lints: ^2.0.1
  very_good_analysis: ^3.1.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/common/
    - assets/common/files/