name: conversational_commerce
description: Filippo Miorin's coding challenge for On
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  bloc: ^8.1.2
  code_builder: ^4.10.0
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  injector: ^3.0.0
  json_annotation: ^4.8.1
  provider: ^6.1.1

  apiClient:
    path: packages/api_client

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^3.1.0
flutter:
  uses-material-design: true